// Level UUID constants - must match backend Const.java
export const LEVEL_UUIDS = {
  LEVEL_1_UUID: "dGV0cmlzLWxldmVsLTF2Y3h2ZnI",
  LEVEL_2_UUID: "bmp1LW5qdS1jb3JyZWxhdGlvbi1sZXZlbC0y",
  LEVEL_3_UUID: "bWluZXN3ZWVwZXItbGV2ZWwtM2RzYWRzYQ",
  LEVEL_4_UUID: "d29yZGxlLWxldmVsLTRkYWRhcw",
  LEVEL_5_UUID: "Y29sb3ItbGV2ZWwtNWNkd3ZjZXY",
  LEVEL_6_UUID: "bnVtYmVyLXNlcXVlbmNlcy1sZXZlbC02",
  LEVEL_7_UUID: "ZnJpZW5kcy1sZXZlbC03",
  LEVEL_8_UUID: "bWluZWNyYWZ0LWxldmVsLTg",
  LEVEL_9_UUID: "Y2F0LWxldmVsLTl2ZmFj",
  LEVEL_10_UUID: "Z2VvZ3JhcGh5LWxldmVsLTEw",
} as const;

// Puzzle UUID constants - must match backend Const.java
export const PUZZLE_UUIDS = {
  PUZZLE_1_UUID: "cHV6emxlLTFkYWNkdmU",
  PUZZLE_2_UUID: "cHV6emxlLTJiZ3J2cg",
  PUZZLE_3_UUID: "ZGVjZWNlcHV6emxlLTM",
  PUZZLE_4_UUID: "dmZydmZycHV6emxlLTQ",
  PUZZLE_5_UUID: "cHV6emxlLTViZ3RidGdidA",
} as const;

// Congratulations UUID constant
export const CONGRATULATIONS_UUID = "Y29uZ3JhdHVsYXRpb25zLWZpbmFs";

// Export individual constants for convenience
export const {
  LEVEL_1_UUID,
  LEVEL_2_UUID,
  LEVEL_3_UUID,
  LEVEL_4_UUID,
  LEVEL_5_UUID,
  LEVEL_6_UUID,
  LEVEL_7_UUID,
  LEVEL_8_UUID,
  LEVEL_9_UUID,
  LEVEL_10_UUID,
} = LEVEL_UUIDS;

export const {
  PUZZLE_1_UUID,
  PUZZLE_2_UUID,
  PUZZLE_3_UUID,
  PUZZLE_4_UUID,
  PUZZLE_5_UUID,
} = PUZZLE_UUIDS;

export const EASTER_EGG_UUIDS = {
  COLOR_EASTER_EGG_UUID: "Y29sb3ItZWFzdGVyLWVnZ3pkYzFx",
  WORDLE_EASTER_EGG_UUID: "d29yZGxlLWVhc3Rlci1lZ2d6hGN6eGM",
  MINESWEEPER_EASTER_EGG_UUID: "bWluZXN3ZWVwZXItZWFzdGVyuWVnZw",
  TETRIS_EASTER_EGG_UUID: "dGV0cmlzLWVhc3Rlci1lZ2dis3RiZ3Q",
  NUMBER_SEQUENCES_EASTER_EGG_UUID: "bnVtYmVyLXNlcXVlbmNlcy1zYXN0ZXItZWdn",
  CORRELATION_EASTER_EGG_UUID: "Y29ycmVsYXRpb24tZWFzdGVttWVnZw",
  FRIENDS_EASTER_EGG_UUID: "ZnJpZW5kcy1lYXN0ZXItZWdnrG9wbG9w",
  MINECRAFT_EASTER_EGG_UUID: "bWluZWNyYWZ0LWVhc3Rlci1rZ2c",
  CAT_EASTER_EGG_UUID: "Y2F0LWVhc3Rlci1lZ2djZGVuyHluaHk",
  GEOGRAPHY_EASTER_EGG_UUID: "Z2VvZ3JhcGh5LWVhc3Rlci1yZ2d6eGM",

} as const;

export const {
  COLOR_EASTER_EGG_UUID,
  WORDLE_EASTER_EGG_UUID,
  MINESWEEPER_EASTER_EGG_UUID,
  TETRIS_EASTER_EGG_UUID,
  NUMBER_SEQUENCES_EASTER_EGG_UUID,
  CORRELATION_EASTER_EGG_UUID,
  FRIENDS_EASTER_EGG_UUID,
  MINECRAFT_EASTER_EGG_UUID,
  CAT_EASTER_EGG_UUID,
  GEOGRAPHY_EASTER_EGG_UUID,
} = EASTER_EGG_UUIDS;
